### ISSUE TITLE
Important KNOWN problems in RIDE (with or without Issues)

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2559]
Fixed? | Description                                                                           | Workaround 
----------|------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------
- [x]     | Lost of data when editing in Text Editor, .resource       | Always use the Save command and not Apply (RIDE needs project reload) Issue #2607 (v2.0.8.dev14)
- [x] | Blocked (in loop) when editing cells with \n in Windows | Until this is corrected, use Text Editor for cells with \n. RIDE needs restart (v2.0.2.dev1)
- [x]     | TestRunner colors PASS/SKIP/FAIL are not updated after changing in preferences | Added the note "Colors will be active after next RIDE restart."
- [x]     | Move up/down rows, fails indentation in  IF/ELSE | This is working OK for FOR, but needs unit tests for IF/ELSE cases and WHILE ... (v2.0.3.2)
- [x]    | Text Editor is missing color setting for keywords (they are always red) | Color setting existed but missing preferences editor (v2.0.1.dev4)
- [x]    | Using a single settings.cfg | Even if we use a venv, the settings are the same. We need to separate this by Python versions, or projects... PR #2760 (v2.1.dev33)
- [x] #2723
- [x] #2815 
- [x]    | Since 2.1dev36 keywords pop-up doc is showing for the cell below the current cell with mouse pointer. | PR #2772 (v2.1.dev38)

**Comment by Tim-QA** [comment]
I'm a fan of RIDE and I'm always happy when there are new and stable versions of it. However, it is not clear to me whether the "/n" problem under Windows is now completely fixed. Currently I have version 2.0.5 installed and see the following problem in the GRID Editor: When editing ${\n} in cells, ${\n\n} is displayed after saving and it keeps duplicating after each editing. Is it still recommended to use the text editor instead of GRID?

**Comment by HelioGuilherme66** [comment]
@Tim-QA 
> When editing ${\n} in cells, ${\n\n} is displayed after saving and it keeps duplicating after each editing. Is it still recommended to use the text editor instead of GRID?

Yes, for now keep using Text Editor.

(I really thought the problem was solved, and I did not considered  ${\\n} in cells,)
