### ISSUE TITLE
Important known issues

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2830]
Cloned from #2559 
Fixed? | Description                                                                           | Workaround 
----------|------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------
- [x]     | Lost of data when editing in Text Editor, .resource       | Always use the Save command and not Apply (RIDE needs project reload) Issue #2607 (v2.0.8.dev14)
- [x] | Blocked (in loop) when editing cells with \n in Windows | Until this is corrected, use Text Editor for cells with \n. RIDE needs restart (v2.0.2.dev1)
- [x]     | TestRunner colors PASS/SKIP/FAIL are not updated after changing in preferences | Added the note "Colors will be active after next RIDE restart."
- [x]     | Move up/down rows, fails indentation in  IF/ELSE | This is working OK for FOR, but needs unit tests for IF/ELSE cases and WHILE ... (v2.0.3.2)
- [x]    | Text Editor is missing color setting for keywords (they are always red) | Color setting existed but missing preferences editor (v2.0.1.dev4)
- [ ]    | Reformat checkbox is not implemented, Preferences Save | Currently. still has old behavior, always reformat
- [x]    | Using a single settings.cfg | Even if we use a venv, the settings are the same. We need to separate this by Python versions, or projects... PR #2760 (v2.1.dev33)
- [ ] #2655
- [x] #2723
- [x] #2815 
- [ ]    | RIDE crashes when detaching Project Explorer | On Windows, when using wxPython < 4.2.2. Use the beta version 4.2.2.
- [x]    | Since 2.1dev36 keywords pop-up doc is showing for the cell below the current cell with mouse pointer. | PR #2772 (v2.1.dev38)
